version: 2
jobs:
  build:
    #working_directory: ~/samplescala
    docker:
      - image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    environment:
      SBT_VERSION: 1.2.8
      SBT_OPTS: "-Xmx1G -XX:MaxMetaspaceSize=384M -XX:+UseCompressedOops"
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: validate
          command: cat /dev/null | sbt validate
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/universal/samplescala.zip
          destination: samplescala
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - "target/resolution-cache"
            - "target/streams"
            - "project/target/resolution-cache"
            - "project/target/streams"
      #- deploy:
      #    command: |
      #        mv target/universal/samplescala.zip $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD
      #        aws s3 cp $CIRCLE_ARTIFACTS/$ARTIFACT_BUILD s3://samplescala.blogs/builds/ --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}

#  post:
#    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
#    - find . -type f -regex ".*/target/test-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
##    - bash <(curl -s https://codecov.io/bash)
